# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/killoboker/CLionProjects/untitled

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/killoboker/CLionProjects/untitled

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/killoboker/CLionProjects/untitled/CMakeFiles /home/killoboker/CLionProjects/untitled/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/killoboker/CLionProjects/untitled/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named HW_TESTS

# Build rule for target.
HW_TESTS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HW_TESTS
.PHONY : HW_TESTS

# fast build rule for target.
HW_TESTS/fast:
	$(MAKE) -f CMakeFiles/HW_TESTS.dir/build.make CMakeFiles/HW_TESTS.dir/build
.PHONY : HW_TESTS/fast

#=============================================================================
# Target rules for targets named HW_1

# Build rule for target.
HW_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HW_1
.PHONY : HW_1

# fast build rule for target.
HW_1/fast:
	$(MAKE) -f CMakeFiles/HW_1.dir/build.make CMakeFiles/HW_1.dir/build
.PHONY : HW_1/fast

#=============================================================================
# Target rules for targets named HW_1_lib

# Build rule for target.
HW_1_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HW_1_lib
.PHONY : HW_1_lib

# fast build rule for target.
HW_1_lib/fast:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/build
.PHONY : HW_1_lib/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Sources/BarGraph.o: Sources/BarGraph.c.o

.PHONY : Sources/BarGraph.o

# target to build an object file
Sources/BarGraph.c.o:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/BarGraph.c.o
.PHONY : Sources/BarGraph.c.o

Sources/BarGraph.i: Sources/BarGraph.c.i

.PHONY : Sources/BarGraph.i

# target to preprocess a source file
Sources/BarGraph.c.i:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/BarGraph.c.i
.PHONY : Sources/BarGraph.c.i

Sources/BarGraph.s: Sources/BarGraph.c.s

.PHONY : Sources/BarGraph.s

# target to generate assembly for a file
Sources/BarGraph.c.s:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/BarGraph.c.s
.PHONY : Sources/BarGraph.c.s

Sources/Vector.o: Sources/Vector.c.o

.PHONY : Sources/Vector.o

# target to build an object file
Sources/Vector.c.o:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/Vector.c.o
.PHONY : Sources/Vector.c.o

Sources/Vector.i: Sources/Vector.c.i

.PHONY : Sources/Vector.i

# target to preprocess a source file
Sources/Vector.c.i:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/Vector.c.i
.PHONY : Sources/Vector.c.i

Sources/Vector.s: Sources/Vector.c.s

.PHONY : Sources/Vector.s

# target to generate assembly for a file
Sources/Vector.c.s:
	$(MAKE) -f CMakeFiles/HW_1_lib.dir/build.make CMakeFiles/HW_1_lib.dir/Sources/Vector.c.s
.PHONY : Sources/Vector.c.s

Tests/Tests.o: Tests/Tests.cpp.o

.PHONY : Tests/Tests.o

# target to build an object file
Tests/Tests.cpp.o:
	$(MAKE) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/Tests/Tests.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Tests/Tests.cpp.o
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/Tests/Tests.cpp.o
	$(MAKE) -f CMakeFiles/HW_TESTS.dir/build.make CMakeFiles/HW_TESTS.dir/Tests/Tests.cpp.o
.PHONY : Tests/Tests.cpp.o

Tests/Tests.i: Tests/Tests.cpp.i

.PHONY : Tests/Tests.i

# target to preprocess a source file
Tests/Tests.cpp.i:
	$(MAKE) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/Tests/Tests.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Tests/Tests.cpp.i
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/Tests/Tests.cpp.i
	$(MAKE) -f CMakeFiles/HW_TESTS.dir/build.make CMakeFiles/HW_TESTS.dir/Tests/Tests.cpp.i
.PHONY : Tests/Tests.cpp.i

Tests/Tests.s: Tests/Tests.cpp.s

.PHONY : Tests/Tests.s

# target to generate assembly for a file
Tests/Tests.cpp.s:
	$(MAKE) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/Tests/Tests.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/Tests/Tests.cpp.s
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/Tests/Tests.cpp.s
	$(MAKE) -f CMakeFiles/HW_TESTS.dir/build.make CMakeFiles/HW_TESTS.dir/Tests/Tests.cpp.s
.PHONY : Tests/Tests.cpp.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/HW_1.dir/build.make CMakeFiles/HW_1.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/HW_1.dir/build.make CMakeFiles/HW_1.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/HW_1.dir/build.make CMakeFiles/HW_1.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... build"
	@echo "... tests"
	@echo "... check"
	@echo "... HW_TESTS"
	@echo "... HW_1"
	@echo "... install/strip"
	@echo "... HW_1_lib"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Sources/BarGraph.o"
	@echo "... Sources/BarGraph.i"
	@echo "... Sources/BarGraph.s"
	@echo "... Sources/Vector.o"
	@echo "... Sources/Vector.i"
	@echo "... Sources/Vector.s"
	@echo "... Tests/Tests.o"
	@echo "... Tests/Tests.i"
	@echo "... Tests/Tests.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

