on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
  test:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: ./tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: tests
  check:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
