on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake build .
  test:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: tests
  coverage:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
      - run: lcov -t "coverageTests" -o coverage.info -c -d CMakeFiles/tests.dir/Tests/
      - run: genhtml -o report coverage.info
  linter:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --quiet Sources/ Headers/
  valgrind:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
      - run: valgrind --track-origins=yes --leak-check=full ./tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main.out


