on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    steps:
      - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [ check ]
    steps:
      - uses: actions/checkout@v2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main.out
  test:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2